[versions]
activity = "1.12.2"
agp = "8.13.2"
core = "3.5.4"
junitBom = "6.0.1"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
junitJupiter = "6.0.2"
playServicesAds = "24.9.0"

[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
core = { module = "com.google.zxing:core", version.ref = "core" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junitBom" }
jupiter-junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }
platform-junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
vintage-junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

