[versions]
activity = "1.12.4"
agp = "9.0.1"
core = "3.5.4"
junit = "6.0.3"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
playServicesAds = "25.0.0"
playServicesWearable = "19.0.0"
junitVersion = "4.13.2"
androidxJunit = "1.3.0"

[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
core = { module = "com.google.zxing:core", version.ref = "core" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
jupiter-junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
platform-junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
vintage-junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine" }
play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }
junit = { group = "junit", name = "junit", version.ref = "junitVersion" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

